# Generated by Django 5.1.7 on 2025-03-29 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outfitly_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AI-generated', 'AI-generated'), ('User-created', 'User-created')], max_length=20)),
                ('is_hijab_friendly', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_path', models.ImageField(blank=True, null=True, upload_to='outfits/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_dates', to='Outfitly_app.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_outfits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=50)),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('All-Season', 'All-Season')], default='All-Season', max_length=15)),
                ('tags', models.TextField(blank=True, null=True)),
                ('photo_path', models.ImageField(blank=True, null=True, upload_to='wardrobe/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='outfit',
            name='selected_items',
            field=models.ManyToManyField(blank=True, related_name='outfit_items', to='Outfitly_app.wardrobe'),
        ),
    ]
