# Generated by Django 5.0 on 2025-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outfitly_app', '0003_category_alter_wardrobe_category_follow_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='modesty_preference',
            field=models.CharField(choices=[('None', 'None'), ('Hijab-Friendly', 'Hijab-Friendly')], default='None', max_length=20),
        ),
    ]
