# Generated by Django 5.0 on 2025-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outfitly_app', '0004_userprofile_bio_userprofile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='outfit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='Outfitly_app.outfittag'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='outfits', to='Outfitly_app.season'),
        ),
    ]
