# Generated by Django 5.0 on 2025-05-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outfitly_app', '0005_outfittag_season_outfit_tags_outfit_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='seasons',
        ),
        migrations.DeleteModel(
            name='OutfitTag',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
