# Generated by Django 5.0 on 2025-05-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outfitly_app', '0006_remove_outfit_tags_remove_outfit_seasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('All-Season', 'All-Season')], default='All-Season', max_length=15),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
